In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_excel('./Data/RawDataEditedTitles.xlsx')
raw_data.head()

,StartDate,EndDate,Progress,Duration,Finished,Familiar,Like_WoM,Like_Soc,Like_Trad,SocResponse,TradResponse,Promo,PersonalInfo,MultipleOffer,MinDiscount,MostPay,Year,Gender
0,Start Date,End Date,Progress,Duration (in seconds),Finished,Familiar,How likely would you be to discover a new pier...,How likely would you be to discover a new pier...,How likely would you be to discover a new pier...,Which social media site would be most likely t...,Which type of traditional media would be most ...,Which type of promotion would most encourage y...,How likely would you be to give away personal ...,How much more likely are you to purchase a ser...,What is the minimum discount percentage that w...,What is the most you're willing to pay for a p...,What year are you at the University of Oregon?,What is your gender?
1,2025-05-01 08:11:29,2025-05-01 08:14:05,100,156,1,AnswerDisplayOrder,4,4,2,2,2,1,NaN,NaN,50,NaN,3,1
2,2025-05-01 09:02:14,2025-05-01 09:03:51,100,96,1,AnswerDisplayOrder,2,1,1,2,3,2,NaN,NaN,23,NaN,3,1
3,2025-05-01 14:13:26,2025-05-01 14:15:30,100,124,1,AnswerDisplayOrder,1,2,2,2,4,1,NaN,NaN,31,NaN,3,1
4,2025-05-01 14:19:37,2025-05-01 14:21:36,100,118,1,AnswerDisplayOrder,3,2,1,2,2,2,NaN,NaN,91,NaN,3,1

In [3]:
data = raw_data.copy().iloc[1:, :]
data['Drop'] = np.zeros(len(data))
data.head()

,StartDate,EndDate,Progress,Duration,Finished,Familiar,Like_WoM,Like_Soc,Like_Trad,SocResponse,TradResponse,Promo,PersonalInfo,MultipleOffer,MinDiscount,MostPay,Year,Gender,Drop
1,2025-05-01 08:11:29,2025-05-01 08:14:05,100,156,1,AnswerDisplayOrder,4,4,2,2,2,1,NaN,NaN,50,NaN,3,1,0.0
2,2025-05-01 09:02:14,2025-05-01 09:03:51,100,96,1,AnswerDisplayOrder,2,1,1,2,3,2,NaN,NaN,23,NaN,3,1,0.0
3,2025-05-01 14:13:26,2025-05-01 14:15:30,100,124,1,AnswerDisplayOrder,1,2,2,2,4,1,NaN,NaN,31,NaN,3,1,0.0
4,2025-05-01 14:19:37,2025-05-01 14:21:36,100,118,1,AnswerDisplayOrder,3,2,1,2,2,2,NaN,NaN,91,NaN,3,1,0.0
5,2025-05-07 23:05:30,2025-05-07 23:06:56,100,86,1,AnswerDisplayOrder,2,3,3,1,2,1,NaN,NaN,40,NaN,2,1,0.0

In [4]:
for i in range(len(data)):
    if data.iloc[i, 0] < pd.Timestamp('2025-05-12 10:00:00'):
        data.at[data.index[i], 'Drop'] = 1  # Faster for single-cell updates

data.head()

,StartDate,EndDate,Progress,Duration,Finished,Familiar,Like_WoM,Like_Soc,Like_Trad,SocResponse,TradResponse,Promo,PersonalInfo,MultipleOffer,MinDiscount,MostPay,Year,Gender,Drop
1,2025-05-01 08:11:29,2025-05-01 08:14:05,100,156,1,AnswerDisplayOrder,4,4,2,2,2,1,NaN,NaN,50,NaN,3,1,1.0
2,2025-05-01 09:02:14,2025-05-01 09:03:51,100,96,1,AnswerDisplayOrder,2,1,1,2,3,2,NaN,NaN,23,NaN,3,1,1.0
3,2025-05-01 14:13:26,2025-05-01 14:15:30,100,124,1,AnswerDisplayOrder,1,2,2,2,4,1,NaN,NaN,31,NaN,3,1,1.0
4,2025-05-01 14:19:37,2025-05-01 14:21:36,100,118,1,AnswerDisplayOrder,3,2,1,2,2,2,NaN,NaN,91,NaN,3,1,1.0
5,2025-05-07 23:05:30,2025-05-07 23:06:56,100,86,1,AnswerDisplayOrder,2,3,3,1,2,1,NaN,NaN,40,NaN,2,1,1.0

In [5]:
data['Familiar'] = data['Familiar'].replace('AnswerDisplayOrder', '')
data.head()

,StartDate,EndDate,Progress,Duration,Finished,Familiar,Like_WoM,Like_Soc,Like_Trad,SocResponse,TradResponse,Promo,PersonalInfo,MultipleOffer,MinDiscount,MostPay,Year,Gender,Drop
1,2025-05-01 08:11:29,2025-05-01 08:14:05,100,156,1,,4,4,2,2,2,1,NaN,NaN,50,NaN,3,1,1.0
2,2025-05-01 09:02:14,2025-05-01 09:03:51,100,96,1,,2,1,1,2,3,2,NaN,NaN,23,NaN,3,1,1.0
3,2025-05-01 14:13:26,2025-05-01 14:15:30,100,124,1,,1,2,2,2,4,1,NaN,NaN,31,NaN,3,1,1.0
4,2025-05-01 14:19:37,2025-05-01 14:21:36,100,118,1,,3,2,1,2,2,2,NaN,NaN,91,NaN,3,1,1.0
5,2025-05-07 23:05:30,2025-05-07 23:06:56,100,86,1,,2,3,3,1,2,1,NaN,NaN,40,NaN,2,1,1.0

In [6]:
df = data[['Familiar']]

# Convert to string, split digits, then one-hot encode
df_encoded = (
    df['Familiar']
    .astype(str)
    .str.split('', expand=True)  # Split into individual digits
    .stack()                     # Convert to long format
    .str.get_dummies()           # One-hot encode
    .groupby(level=0).max()      # Combine rows back
    .add_prefix('choice_')       # Rename columns (e.g., 'choice_6')
)

# Join back to original DataFrame
df = df.join(df_encoded)
df
keeper_cols = df[['choice_6', 'choice_7', 'choice_8']]
keeper_cols = keeper_cols.rename(columns={'choice_6':'FamiliarHP', 'choice_7':'FamiliarA51P', 'choice_8':'FamiliarDHP'})
keeper_cols

    FamiliarHP  FamiliarA51P  FamiliarDHP
1            0             0            0
2            0             0            0
3            0             0            0
4            0             0            0
5            0             0            0
..         ...           ...          ...
95           1             0            0
96           0             0            0
97           0             0            0
98           0             0            0
99           1             0            0

[99 rows x 3 columns]

In [7]:
data = data.join(keeper_cols)
data.head()

,StartDate,EndDate,Progress,Duration,Finished,Familiar,Like_WoM,Like_Soc,Like_Trad,SocResponse,...,PersonalInfo,MultipleOffer,MinDiscount,MostPay,Year,Gender,Drop,FamiliarHP,FamiliarA51P,FamiliarDHP
1,2025-05-01 08:11:29,2025-05-01 08:14:05,100,156,1,,4,4,2,2,...,NaN,NaN,50,NaN,3,1,1.0,0,0,0
2,2025-05-01 09:02:14,2025-05-01 09:03:51,100,96,1,,2,1,1,2,...,NaN,NaN,23,NaN,3,1,1.0,0,0,0
3,2025-05-01 14:13:26,2025-05-01 14:15:30,100,124,1,,1,2,2,2,...,NaN,NaN,31,NaN,3,1,1.0,0,0,0
4,2025-05-01 14:19:37,2025-05-01 14:21:36,100,118,1,,3,2,1,2,...,NaN,NaN,91,NaN,3,1,1.0,0,0,0
5,2025-05-07 23:05:30,2025-05-07 23:06:56,100,86,1,,2,3,3,1,...,NaN,NaN,40,NaN,2,1,1.0,0,0,0

In [8]:
data.to_excel('./Data/cleaned_data.xlsx', index=False)